version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: notes-db
    restart: always
    environment:
      MYSQL_DATABASE: notes
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  django_app:
    image: 569034625244.dkr.ecr.us-east-1.amazonaws.com/myapp/repo-django:${IMAGE_TAG}
    container_name: django-app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: notes
      DB_USER: notesuser
      DB_PASS: notepass
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn django_notes_app.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - app-network

  nginx:
    image: 569034625244.dkr.ecr.us-east-1.amazonaws.com/myapp/repo-nginx:${IMAGE_TAG}
    container_name: nginx
    restart: always
    depends_on:
      - django_app
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
